name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install texlive
        run: sudo apt-get update && sudo apt-get install texlive-full 

      - uses: actions/checkout@v2

      - name: Run latexmk
        run: latexmk
    
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: ${GITHUB_WORKSPACE}/um-thesis.pdf
