name: ubuntu-20.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install texlive
        run: sudo apt-get update && sudo apt-get install texlive-latex-base texlive-xetex latexmk biber

      - uses: actions/checkout@v2

      - name: Run latexmk
        run: |
          latexmk -c
          latexmk

      - uses: actions/upload-artifact@v2
        with:
          name: Compiled pdf
          path: um-thesis.pdf
