name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install texlive
        run: sudo apt-get update && sudo apt-get install texlive-full 

      - uses: actions/checkout@v2

      - name: Run latexmk
        run: |
          pwd
          ls
          latexmk um-thesis.tex

      - uses: actions/upload-artifact@v2
        with:
          name: Compiled pdf
          path: um-thesis.pdf
